### PR TITLE
error message includes required memory mb

### LINKED ISSUE #1491: Show required memory to execute a circuit
Qiskit Aer version: latest
    Python version: 3.9.5
    Operating system:

### What is the expected behavior?

I am executing circuit with different sizes and I want to know which is the biggest circuit that I can execute with the available memory.

I get this message: 

qiskit.exceptions.QiskitError: 'ERROR:  [Experiment 0] Insufficient memory to run circuit circuit-10 using the statevector simulator. ,  ERROR: Insufficient memory to run circuit circuit-10 using the statevector simulator.'

The expected behaviour is to know which is the required memory to execute the circuit. Something similar to:

qiskit.exceptions.QiskitError: 'ERROR:  [Experiment 0] Memory available [SYSTEM_MEMORY_GB]  gb is insufficient to run circuit circuit-10 which requires [required_memory_mb] mb using the statevector simulator. ,  ERROR: Insufficient memory to run circuit circuit-10 using the statevector simulator.'

I suppose that it is just to get the value of the variable used to do the comparison (if required_memory > available_memory) raise exception. But I can't find the variable required_memory.

Thank you!

### PR DESCRIPTION
**Pull request by hhorii**
### Summary

Add more messages in error status when memory is short

### Details and comments

To fix #1491.

### CODE REVIEW

File: src/controllers/aer_controller.hpp [hunk 1]
```diff
@@ -1922,10 +1922,14 @@ bool Controller::validate_state(const state_t &state, const Circuit &circ,
...
     size_t mem_size = (sim_device_ == Device::GPU) ? max_memory_mb_ + max_gpu_memory_mb_ : max_memory_mb_;
     memory_valid = (required_mb <= mem_size);
-  }
-  if (throw_except && !memory_valid) {
-    error_msg << "Insufficient memory to run circuit " << circ_name;
-    error_msg << " using the " << state.name() << " simulator.";
+    if (throw_except && !memory_valid) {
+      error_msg << "Insufficient memory to run circuit " << circ_name;
+      error_msg << " using the " << state.name() << " simulator.";
+      error_msg << " required_memory_mb=" << required_mb << ", max_memory_mb=" << max_memory_mb_;
```
Comment (jakelishman) [inline src/controllers/aer_controller.hpp:1928]: We could make this error a little nicer for the reader by doing something like
```c++
error_msg << " Required memory: " << required_mb << "M, max memory: " << max_memory_mb << "M"
```
so it shows as
```text
Insufficient memory to run circuit .... Required memory: 112358M, max memory: 4096M
```
rather than using the names of the internal variables.

(and similar for the GPU bit below)

**Review by jakelishman — COMMENTED** [review]
Mostly looks fine to me, just a minor comment about the error message.

**Review by jakelishman — APPROVED** [review]
