### PR TITLE
use `omp_set_max_active_levels` instead of `omp_set_nested`

### LINKED ISSUE #1751: OMP: Info #271: omp_set_nested routine deprecated
### Informations

- **Qiskit Aer version**: 0.11.2
- **Python version**: 3.10.4
- **Operating system**: 13.2.1

### What is the current behavior?
Deprecation warning

### Steps to reproduce the problem

```
import qiskit
from qiskit_experiments.library import StateTomography

# For simulation
from qiskit.providers.aer import AerSimulator

import numpy as np

qc_bell = qiskit.QuantumCircuit(2)
qc_bell.h(0)
qc_bell.cx(0, 1)

#Simulate the outcome
qc_bell.save_statevector()          
qobj = qiskit.assemble(qc_bell)     
sim = qiskit.Aer.get_backend('aer_simulator') 

sim.options.max_parallel_experiments=3  # Commenting out line this removes warning

result = sim.run(qobj).result() 


# QST Experiment
qstexp1 = StateTomography(qc_bell)
shotVal = 1e2
qstdata1 = qstexp1.run(sim, shots=shotVal, seed_simulation=100).block_for_results()
```

### What is the expected behavior?
No warning 

### Suggested solutions
Warning suggests use `omp_set_max_active_levels instead.`

### PR DESCRIPTION
**Pull request by hhorii**
### Summary

Fix #1751

### Details and comments

This PR uses `omp_set_max_active_levels` instead of `omp_set_nested` which shows warnings in some environment.

### CODE REVIEW

File: src/controllers/aer_controller.hpp [hunk 1]
```diff
@@ -963,7 +963,11 @@ Result Controller::execute(std::vector<Circuit> &circuits,
       parallel_nested_ = true;
 
       // nested should be set to zero if num_threads clause will be used
+#if defined(_WIN64) || defined(_WIN32)
       omp_set_nested(0);
+#else
+      omp_set_max_active_levels(0);
+#endif
```
Comment (jakelishman) [inline src/controllers/aer_controller.hpp:970]: This maybe wants to gate on `#if defined(_OPENMP) && _OPENMP >= 200805` instead (that's a check that we've got OpenMP 3.0+) - it's a bit more precise about what we actually need.

**Review by jakelishman — COMMENTED** [review]
There also appears to be some weirdness in the `src/misc/{gcc,clang}_omp_symbols.hpp` that might need looking at too.  I don't know the purpose of those files, though.

**Review by jakelishman — APPROVED** [review]
This looks right to me, though full disclaimer I don't have a C++ developer Windows system to verify on.
