### PR TITLE
Fix gate fusion bug

### LINKED ISSUE #604: ERROR: Stabilizer::State::invalid instruction 'fusion'.
### Informations

- **Qiskit Aer version**: master
- **Python version**: 3.6
- **Operating system**: Linux

### What is the current behavior?

`ERROR: Stabilizer::State::invalid instruction 'fusion'.` for a simple innocent circuit.

### Steps to reproduce the problem

```
import qiskit
from qiskit.providers.aer.extensions.snapshot_expectation_value import *
import numpy as np

n = 25
circ = qiskit.QuantumCircuit(n, n)
circ.h(0)
for i in range(n-1):
    circ.cx(0, i+1)
circ.snapshot_expectation_value('hi', [[1, 'Z']], [0])

sim = qiskit.Aer.get_backend('qasm_simulator')
res = qiskit.execute(circ, sim, shots=100).result()

print(res)
```

This works fine for `n<=19` (expectation value is 0). Starting from `n=20`, execution fails with the error that's in the issue's title.

### What is the expected behavior?

Work always

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

Fixes #604 

1. Fixes bugs in gate fusion transpilation pass where the pass was not checking that unitary gates (`OpType::matrix`) where in the allowed instructions of simulator. This was causing simulations on the stabilizer simulator to fail for example when fusion was enabled automatically.

2. Fixes name of fusion instruction to be "unitary" rather than "fusion", and instead uses "fusion" is as the unitary gate label.

3. Adds exception to MPS simulator if it tries to apply a larger than 2-qubit gate. Previously this was silently ignoring the instruction.

### CODE REVIEW

File: src/framework/operations.hpp [hunk 1]
```diff
@@ -196,6 +196,13 @@ class OpSet {
   // Add additional ops to the opset
   void insert(const std::vector<Op> &ops);
 
+  //-----------------------------------------------------------------------
+  // Check if operations are in all in the OpSet
+  //-----------------------------------------------------------------------
+
```
Comment (yaelbh) [inline src/framework/operations.hpp]: "in all" is a typo

**Comment by chriseclectic** [comment]
I think we should just disable unitary matrices from MPS simulator. It doesn't actually support the instruction as the instruction is defined as a general N-qubit matrix, and the exception raising I added here for >2Q is basically a hack. Especially since you mentioned in the issue that it is much slower for applying 1 and 2Q unitaries than other gates anyway. We can add it back as a supported instruction if support is added for general N-qubit unitaries.

**Comment by yaelbh** [comment]
@merav-aharoni what do you think about disabling unitaries (including 1Q and 2Q) for MPS?  @yehuda-naveh ?

**Comment by merav-aharoni** [comment]
I think it would be a shame to disable the unitary gates for 1 and 2 qubits, since they do work, and it would mean many circuits would not be able to run on mps. I would rather add the functionality for N qubit unitaries. It shouldn't be too much trouble to implement, as it is a generalization of 3 qubit gates, which are already supported in principle (at least ccx is).

**Comment by chriseclectic** [comment]
Any 1 and 2-qubit unitary can be synthesised into CX and u3 gates by terra compiler, so those circuits would still run if we removed it.

**Comment by merav-aharoni** [comment]
So I guess it is okay to disable support for general unitaries. 
In addition, I agree with @yaelbh that we should disable fusion for MPS, because I believe that would harm performance.

File: src/transpile/fusion.hpp [hunk 2]
```diff
@@ -367,7 +368,7 @@ op_t Fusion::generate_fusion_operation(const std::vector<op_t>& fusioned_ops) co
     U = u_tmp;
   }
 
-  return Operations::make_fusion(sorted_qubits, U, fusioned_ops);
+  return Operations::make_unitary(sorted_qubits, U, std::string("fusion"));
```
Comment (atilag) [inline src/transpile/fusion.hpp]: In C++14 we have a neat feature for literal strings:
```c++
 return Operations::make_unitary(sorted_qubits, U, "fusion"s);
```

Comment (atilag) [reply src/transpile/fusion.hpp]: Actually, one has to import from a namespace to use it:
```c++
using namespace std::string_literals;
```
... it's ugly.
