### PR TITLE
Fix required memory checks for QasmSimulator with custom method

### LINKED ISSUE #755: Segmentation Fault during repeated execution of circuit using `density_matric_gpu` simulator)
### Informations

- **Qiskit Aer version**:
```python
{'qiskit-terra': '0.14.1',
 'qiskit-aer': '0.5.1',
 'qiskit-ignis': '0.3.0',
 'qiskit-ibmq-provider': '0.7.1',
 'qiskit-aqua': '0.7.1',
 'qiskit': '0.19.2'}
```
- **Python version**: 3.6.9 
- **Operating system**: Ubuntu 19.04

### What is the current behavior?

After repeated execution of circuits (a common scenario found in variational algorithm),
- the density matrix CPU simulator will cause `segmentation fault (core dumped)`
- the density matric GPU simulator will cause 
```bash
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument
[1]    11839 abort (core dumped)
```

### Steps to reproduce the problem

A example script:

```python
import qiskit as qk
import time

qc = qk.QuantumCircuit(20, 1)
[qc.h(_) for _ in range(20)]
qc.measure(0, 0)
bkd = qk.Aer.get_backend("qasm_simulator")
option = {"method": "density_matrix_gpu"}  # or density_matrix_cpu
i = 0
while True:
    i += 1
    print("Looping: ", i)
    qk.execute(qc, bkd, backend_options=option)
```
The error typically happen around 100 to 200 loops.

### What is the expected behavior?

The simulator should be able to indefinitely execute the script.

### Suggested solutions

Not sure.

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

Fixes issue where memory requirements of simulation were not being checked on the QasmSimulator when using a non-automatic simulation method.

Closes #755

### CODE REVIEW

File: src/simulators/density_matrix/densitymatrix_state.hpp [hunk 1]
```diff
@@ -352,12 +352,8 @@ template <class densmat_t>
 size_t State<densmat_t>::required_memory_mb(uint_t num_qubits,
                                             const std::vector<Operations::Op> &ops)
                                             const {
-  // An n-qubit state vector as 2^n complex doubles
-  // where each complex double is 16 bytes
   (void)ops; // avoid unused variable compiler warning
```
Comment (atilag) [inline src/simulators/density_matrix/densitymatrix_state.hpp:355]: This is not part of your changes, but seeing this line, it makes clear that we need an override of this method.

File: releasenotes/notes/fix-required-memory-check-0a138e0478d8ff32.yaml [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+fixes:
+  - |
+    Fixes issue where memory requirements of simulation were not being checked
+    on the QasmSimulator when using a non-automatic simulation method.
```
Comment (atilag) [inline releasenotes/notes/fix-required-memory-check-0a138e0478d8ff32.yaml:5]: I thought this was automatically generated when creating the release?

Comment (chriseclectic) [reply releasenotes/notes/fix-required-memory-check-0a138e0478d8ff32.yaml:5]: I thought you still needed these since they have them in Terra, but maybe @mtreinish knows?

Comment (mtreinish) [reply releasenotes/notes/fix-required-memory-check-0a138e0478d8ff32.yaml:5]: Yes this is still needed. The changelog is automated now, but release documentation still needs to be written. The previous changelog was serving double duty as release documentation (frankly quite poorly). See the contributing docs on this: https://github.com/Qiskit/qiskit-aer/blob/master/CONTRIBUTING.md#release-notes (the changelog section above it mentions the changelog autogeneration)
